CREATE TABLE "STATEMENT" (
	"ID" TEXT,
	"VALUE" TEXT NOT NULL,
	"SOURCE" TEXT,
	"TARGET" TEXT,
	FOREIGN KEY("SOURCE") REFERENCES "ITEM"("ID"),
	FOREIGN KEY("TARGET") REFERENCES "ITEM"("ID"),
	PRIMARY KEY("ID")
)

