CREATE TABLE "ITEM" (
	"ID" TEXT,
	"LABEL" TEXT NOT NULL,
	"DISAMBIGUATION" TEXT NOT NULL DEFAULT '',
	"DESCRIPTION" TEXT,
	"URL" TEXT,
	"ATTRIBUTES" TEXT,
	"ALIASES" TEXT,
	"ENTRY_POINT_ITEM" INTEGER,
	UNIQUE(LABEL,DISAMBIGUATION),
	PRIMARY KEY("ID")
)